<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>stg</string>
		<string>sti</string>
		<string>st</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(\[|&lt;&lt;|\$if(.*)\$)\s*$</string>
	<key>foldingStopMarker</key>
	<string>(\]|&gt;&gt;|\$endif\$)</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>StringTemplate</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.StringTemplate</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)(\(\w*\))?\s*::=</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*\n</string>
			<key>name</key>
			<string>comment.line.double-slash.StringTemplate</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#map</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.java</string>
				</dict>
			</dict>
			<key>match</key>
			<string>/\*\*/</string>
			<key>name</key>
			<string>comment.block.empty.StringTemplate</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(/\*|\$!)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.java</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\*/|!\$)</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.java</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.java</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*((//).*$\n?)</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\$</string>
			<key>end</key>
			<string>\$</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>{.*}</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>embedded-code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#php</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#smarty</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#python</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>\b(group|implements)\b</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
		<key>map</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.begin.StringTemplate</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.end.StringTemplate</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.dictionary.StringTemplate</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(default|key)\b</string>
					<key>name</key>
					<string>keyword.control.StringTemplate</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>end</key>
			<string>(")</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.StringTemplate</string>
	<key>uuid</key>
	<string>51825919-0BAE-476F-8679-B2361CDAC9B7</string>
</dict>
</plist>
